name: Backend

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - converted_to_draft

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.22.x"]
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version

      - name: Run audit
        run: go mod verify

      - name: Run build
        run: go build .

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: "-no-fail -fmt sarif -out results.sarif ./..."
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - name: Run go vet
        run: go vet ./...

      - name: Tests
        uses: robherley/go-test-action@v0

  build:
    runs-on: ubuntu-latest
    needs: audit
    strategy:
      matrix:
        go-version: ["1.22.x"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
