name: Backend

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, converted_to_draft]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
      - run: go version
        working-directory: ./backend
      - run: go mod verify
        working-directory: ./backend
      - run: go vet ./...
        working-directory: ./backend
      - run: go fmt ./...
        working-directory: ./backend
      - run: go build -v ./...
        working-directory: ./backend
      - uses: robherley/go-test-action@v0
        with:
          moduleDirectory: ./backend
          testArguments: ./...
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: "-no-fail -fmt sarif -out results.sarif ./..."
          working-directory: ./backend
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

  build:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
      - run: go build ./...
        working-directory: ./backend
