name: CI
on: [push]
jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Code
      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: true
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm exec playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 3

  eslint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Code
      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: true
      - name: Run Eslint
        run: pnpm run lint

  prettier:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Code
      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: true
      - name: Run Prettier
        run: pnpm exec prettier --write  .

  vercel:
    runs-on: ubuntu-latest
    needs: [prettier, eslint, playwright]

    steps:
      - uses: actions/checkout@v3
        name: Checkout Code
      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: true
      - name: Deploy to Staging 
        id: deploy-vercel-staging
        uses: amondnet/vercel-action@v25
        with:
            vercel-token: ${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Production 
        uses: amondnet/vercel-action@v25
        id: deploy-vercel-production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'